apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../infrastructure/homelab
  - ../../apps/homelab

patches:
  - target:
      group: ""
      version: v1
      kind: Service
      name: portainer-agent
      namespace: portainer
    patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer
