---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb-system

resources:
  - ../base/metallb-native.yaml
  - ../base/portainer-agent-k8s-lb.yaml

patches:
  - path: metallb-patches.yaml
