---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - metallb-native.yaml
  - portainer-agent-k8s-lb.yaml

patchesJson6902:
  - target:
      group: metallb.io
      version: v1beta1
      kind: IPAddressPool
      name: default
      namespace: metallb-system
    patch: |-
      - op: replace
        path: /spec/addresses
        value:
          - 192.168.1.245-192.168.1.250
  - target:
      group: metallb.io
      version: v1beta1
      kind: L2Advertisement
      name: default
      namespace: metallb-system
    patch: |-
      - op: replace
        path: /spec/ipAddressPools
        value:
          - default
