---
apiVersion: v1
kind: Secret
metadata:
    name: test-secret
    namespace: default
stringData:
    foo: ENC[AES256_GCM,data:orzg,iv:EQfLhWtOyPGiApV4dRYZzWpiqVgPV0ZDGzfXUD8mfBg=,tag:L/aLkNyXpv8ImLF2rQ6xoQ==,type:str]
sops:
    age:
        - recipient: age1v6ewuuyxlt7uug0jfnfwcyz7tarh07ygsyyd6q8ade2st5qhk4eqvt66vd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmK0hkYlg0aFMrZWd6Qzd0
            WDJJRXhSOVhiVzNGbVh1cnhEakpFSHBxQlFNCkNHbSs4a3dSTTJnRVFlTnRUcTdp
            Y0VWUHhOMkFob3JVUnZrTStlT2RPTXcKLS0tIGRrcWFhZHMyTXUxTnZqQlJNSUl2
            eGREMm10VmVhdnpDeVl4Qk1yV2NZVk0K8qHdYu5t7mPnNQk2ObM1Re6g9XPMbqk6
            X6kPUjvJAHiAkyafQ/9UCzPW+3SaBz6Bva0jU0fcyHgtLcu+3Fo92A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T00:01:35Z"
    mac: ENC[AES256_GCM,data:df/ibupblZTztZw+Imsgi66ykeB26UJazZdDv5zNFGf5bppLE27QwHbQPgZV4Y2aVEQq6kjnS6L76bp3Jh9jOTlU/VvL0H8aYbka46N4ddP2qr52ShrkRccwtREac5iOTwykoVg3TmhlYdANVNaqqE/VGf1HO11oJ/WNXefoy9U=,iv:5JsB0RtKaFpMVnlG1oajd8oQ+FQTVIertEXJl7gI7Z4=,tag:v4tKr9sCfUYExtSc1GRneg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
