---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - cloudflare-api-token-secret.yaml
  # Temporarily until secret management is sorted
  # Secret is managed out-of-band in /secrets/cloudflare-api-token-secret.yaml
  - clusterissuer.yaml
